# Parameters for config params.toml
[TermsAndPrivacy]
    company_name = "Your company"
    contact_email = "contact email for your company"
    website = "Website URL"
    contact_dpo_email = "Data Protection Officer Email"
    contact_dpo_phone = "Data Protection Officer Phone number"
    location_address = "Your company address"
