# Parameters for config params. TOML file
[TermsAndPrivacy]
    company_name = "Your company"
    company_email = "contact email for your company"
    website = "Website URL"
    company_dpo_email = "Data Protection Officer Email"
    company_dpo_telephone = "Data Protection Officer Phone number"
    location_address = "Your company address"
    company_address = "Your company address"
    company_telephone = "Your company telephone"
